language: php

php:
  # 5.4
  - 5.5
  # 5.6

env:
  - DB=mysql

before_script:
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'log_errors = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'error_log = /home/travis/build/jfx/my-agile-project/app/logs/php_error.log' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir app/cache
  - chmod 777 app/cache
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction

script: phpunit -c app

after_failure: 
  - cat app/logs/test.log
  - cat /home/travis/build/jfx/my-agile-project/app/logs/php_error.log
