language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  # echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir app/cache
  - chmod 777 app/cache
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction

script: phpunit -c app

after_failure: 
  - cat app/logs/test.log
  - find / -name 'error.log' 2> /dev/null
