parameters:
#    map_core.example.class: Map\CoreBundle\Example

services:
    map.CoverageListener:
        class: Map\CoreBundle\Service\CoverageListener
        arguments: [ '@kernel', '%app.codeCoverage%' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    map.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            # first argument: a named array of menues:
            - { leftmenu: '@map.navbar_main_menu=', rightmenu: '@map.navbar_right_menu=' }
            # second argument: a named array of FormType Classes
            - { searchform: Map\CoreBundle\Form\MenuSelectType }
            # third argument: a named array of options
            - { title: "My Agile Project", titleRoute: "home_index", inverse: true, fixedTop: true, isFluid: true, template:MopaBootstrapBundle:Navbar:navbar.html.twig }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    map.navbar_menu_builder:
        class: Map\CoreBundle\Menu\NavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    map.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: map.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    map.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: map.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    map.localeDate:
        class: Map\CoreBundle\Extensions\LocaleDateExtension
        arguments: [ '@service_container' ]
        tags:
            - { name: twig.extension }
