map_domain:
    resource: "@MapDomainBundle/Resources/config/routing.yml"
    prefix:   /

map_home:
    resource: "@MapHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

map_user:
    resource: "@MapUserBundle/Resources/config/routing.yml"
    prefix:   /

map_core:
    resource: "@MapCoreBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
