parameters:
#    map_project.example.class: Map\ProjectBundle\Example

services:
#    map_project.example:
#        class: %map_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
