parameters:
#    map_user.example.class: Map\UserBundle\Example

services:
#    map_user.example:
#        class: %map_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
