parameters:
#    map_user.example.class: Map\UserBundle\Example

services:
    map_user.updatecontext4user:
        class: Map\UserBundle\Service\UpdateContext4User
        arguments: [ '@security.context', '@doctrine.orm.entity_manager', '@fos_user.user_manager' ]
        scope: request

    map_user.AuthenticationListener:
        class: Map\UserBundle\Service\AuthenticationListener
        arguments: [ '@doctrine.orm.entity_manager', '@fos_user.user_manager' ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthenticationSuccess }

    map_user.passwordFactory:
        class: Map\UserBundle\Service\PasswordFactory
        arguments: [ '%app.defaultPasswordLength%' ]
        scope: request

    map_user.resetting.form.type:
        class: Map\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: map_userbundle_resettingformtype }
