parameters:
#    map_user.example.class: Map\UserBundle\Example

services:
    map_user.updatedomain4user:
        class: Map\UserBundle\Service\UpdateDomain4User
        arguments: ['@security.context', '@doctrine.orm.entity_manager', '@fos_user.user_manager']
        scope: request

    map_user.AuthenticationListener:
        class: Map\UserBundle\Service\AuthenticationListener
        arguments: ['@doctrine.orm.entity_manager', '@fos_user.user_manager']
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthenticationSuccess }
