map_domain_homepage:
    resource: "@MapDomainBundle/Resources/config/routing/domain.yml"
    prefix:   /domain

map_dm-resource_homepage:
    resource: "@MapDomainBundle/Resources/config/routing/resource.yml"
    prefix:   /dm-resource
