parameters:
#    map_domain.example.class: Map\DomainBundle\Example

services:
    map_user.domaininfo:
        class: Map\DomainBundle\Service\DomainInfo
        arguments: [ '@doctrine.orm.entity_manager' ]
        scope: request
