parameters:
#    map_domain.example.class: Map\DomainBundle\Example

services:
#    map_domain.example:
#        class: %map_domain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
