adminApplication_index:
    pattern:  /
    defaults: { _controller: "MapAdminBundle:Application:index" }
    
adminApplication_view:
    pattern:  /{id}
    defaults: { _controller: "MapAdminBundle:Application:view" }
    requirements:
        id:  \d+
    
adminApplication_add:
    pattern:  /add
    defaults: { _controller: "MapAdminBundle:Application:add" }
    
adminApplication_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "MapAdminBundle:Application:edit" }
    requirements:
        id:  \d+
    
adminApplication_del:
    pattern:  /del/{id}
    defaults: { _controller: "MapAdminBundle:Application:del" }
    requirements:
        id:  \d+