<?php

namespace Map\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function findAllOrderByName()
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->orderBy('a.name');
        
        $results = $queryBuilder->getQuery()->getResult();
        
        return $results;
    }
}
