<?php
/**
 * User Domain Role entity repository class.
 *
 * LICENSE : This file is part of My Agile Project.
 *
 * My Agile Project is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * My Agile Project is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category  MyAgileProject
 * @package   User
 * @author    Francois-Xavier Soubirou <soubirou@yahoo.fr>
 * @copyright 2013 Francois-Xavier Soubirou
 * @license   http://www.gnu.org/licenses/   GPLv3
 * @link      http://www.myagileproject.org
 * @since     2
 *
 */

namespace Map\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Map\DomainBundle\Entity\Domain;

/**
 * UserDmRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDmRoleRepository extends EntityRepository
{
    public function findUserByDomain(Domain $domain)
    {
        $qb = $this->createQueryBuilder('udr')
            ->join('udr.role', 'r')
            ->addSelect('r.label as role')
                     
            ->join('udr.domain', 'd')
            ->addSelect('d')
            ->where('d.id = :domainId')
            ->setParameter('domainId', $domain->getId())
            ->join('udr.user', 'u')
            ->addSelect('u.id, u.name, u.firstname, u.displayname')
            ->orderBy('u.name, u.firstname', 'ASC')
        ;
        $results = $qb->getQuery()->getResult();
        
        return $results;
    }
    
        public function findByUserIdDomainId($userId, $domainId)
    {
        $qb = $this->createQueryBuilder('udr')
            ->join('udr.user', 'u')
            ->join('udr.domain', 'd')
            ->where('u.id = :userId')
            ->andWhere('d.id = :domainId')
            ->setParameter('userId', $userId)
            ->setParameter('domainId', $domainId);
        
        $result = $qb->getQuery()->getSingleResult();
        
        return $result;
    }
    
    public function getQBUserIdByDomainParam($param)
    {
        $qb = $this->_em->createQueryBuilder();
        
        $qb ->select('userqb.id')
            ->from($this->_entityName, 'udr')
            ->join('udr.user', 'userqb')
            ->join('udr.domain', 'domainqb')
            ->where('domainqb.id = :'.$param);
  
        return $qb;
    }
}